"""reduce refresh token index length

Revision ID: 1580ac97af28
Revises: 137f44ba434b
Create Date: 2026-09-06 22:56:06.389839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1580ac97af28'
down_revision: Union[str, Sequence[str], None] = '137f44ba434b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=191),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'refresh_token',
               existing_type=sa.String(length=191),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
