"""add is_paid to appointment

Revision ID: 1cb97ea7f42b
Revises: 44f6cad9a23d
Create Date: 2026-08-23 13:59:50.041161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb97ea7f42b'
down_revision: Union[str, Sequence[str], None] = '44f6cad9a23d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('is_paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'is_paid')
    # ### end Alembic commands ###
