"""add customer_id to the discount table

Revision ID: 376834d8bc32
Revises: 5e4eb3353e44
Create Date: 2026-08-18 11:22:30.975642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "376834d8bc32"
down_revision: Union[str, Sequence[str], None] = "5e4eb3353e44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "discounts", "customers", ["customer_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "discounts", type_="foreignkey")
    op.drop_column("discounts", "customer_id")
    # ### end Alembic commands ###
