"""remove uniq  salon_id

Revision ID: 44f6cad9a23d
Revises: 99fc23498f64
Create Date: 2026-08-21 17:41:59.318357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "44f6cad9a23d"
down_revision: Union[str, Sequence[str], None] = "99fc23498f64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint("customers_ibfk_2", "customers", type_="foreignkey")

    op.drop_index("ix_customers_salon_id", table_name="customers")

    op.create_index("ix_customers_salon_id", "customers", ["salon_id"], unique=False)

    op.create_foreign_key(
        "customers_ibfk_2", "customers", "salons", ["salon_id"], ["id"]
    )

    op.drop_constraint("services_ibfk_1", "services", type_="foreignkey")

    op.drop_index("ix_services_salon_id", table_name="services")

    op.create_index("ix_services_salon_id", "services", ["salon_id"], unique=False)

    op.create_foreign_key("services_ibfk_1", "services", "salons", ["salon_id"], ["id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_services_salon_id"), table_name="services")
    op.create_index(op.f("ix_services_salon_id"), "services", ["salon_id"], unique=True)
    op.drop_index(op.f("ix_customers_salon_id"), table_name="customers")
    op.create_index(
        op.f("ix_customers_salon_id"), "customers", ["salon_id"], unique=True
    )
    # ### end Alembic commands ###
