"""add salon Id to appointment

Revision ID: 493e2933c928
Revises: 57059b6bd082
Create Date: 2026-08-14 13:31:57.250125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "493e2933c928"
down_revision: Union[str, Sequence[str], None] = "57059b6bd082"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key(None, "appointments", "salons", ["salon_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "appointments", type_="foreignkey")
    op.drop_column("appointments", "salon_id")
    # ### end Alembic commands ###
