"""create salon and owner

Revision ID: 57059b6bd082
Revises: eaa15edf2fec
Create Date: 2026-08-14 12:46:46.120499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '57059b6bd082'
down_revision: Union[str, Sequence[str], None] = 'eaa15edf2fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_owners_id'), 'owners', ['id'], unique=False)
    op.create_table('salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), nullable=True),
    sa.Column('UpdatedAt', sa.DateTime(), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.Column('DeletedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salons_id'), 'salons', ['id'], unique=False)
    op.drop_constraint(op.f('appointments_ibfk_2'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('appointments_ibfk_2'), 'appointments', 'services', ['service_id'], ['id'])
    op.drop_index(op.f('ix_salons_id'), table_name='salons')
    op.drop_table('salons')
    op.drop_index(op.f('ix_owners_id'), table_name='owners')
    op.drop_table('owners')
    # ### end Alembic commands ###
