"""remove firstname and laastname from user and add the to customer table

Revision ID: 74f131812985
Revises: 1cb97ea7f42b
Create Date: 2026-08-24 12:41:05.890603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '74f131812985'
down_revision: Union[str, Sequence[str], None] = '1cb97ea7f42b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('first_name', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    # ### end Alembic commands ###
