"""updated service table

Revision ID: 87542b03780b
Revises: 7b8e991d3ff1
Create Date: 2026-08-09 10:14:43.546417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87542b03780b'
down_revision: Union[str, Sequence[str], None] = '7b8e991d3ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('CreatedAt', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('UpdatedAt', sa.DateTime(), nullable=True))
    op.drop_column('services', 'description')
    op.drop_column('services', 'price')
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('created_at', mysql.DATETIME(), nullable=False))
    op.add_column('services', sa.Column('updated_at', mysql.DATETIME(), nullable=False))
    op.add_column('services', sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('services', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_column('services', 'UpdatedAt')
    op.drop_column('services', 'CreatedAt')
    # ### end Alembic commands ###
