"""add salon_id to customer and service

Revision ID: 99fc23498f64
Revises: 376834d8bc32
Create Date: 2026-08-21 17:27:45.829877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99fc23498f64'
down_revision: Union[str, Sequence[str], None] = '376834d8bc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customers_salon_id'), 'customers', ['salon_id'], unique=True)
    op.create_foreign_key(None, 'customers', 'salons', ['salon_id'], ['id'])
    op.add_column('services', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_services_salon_id'), 'services', ['salon_id'], unique=True)
    op.create_foreign_key(None, 'services', 'salons', ['salon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_salon_id'), table_name='services')
    op.drop_column('services', 'salon_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_salon_id'), table_name='customers')
    op.drop_column('customers', 'salon_id')
    # ### end Alembic commands ###
