"""add back_percent to salon table

Revision ID: ae46eccc56b3
Revises: 74f131812985
Create Date: 2026-08-25 17:56:55.378128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae46eccc56b3'
down_revision: Union[str, Sequence[str], None] = '74f131812985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('back_percent', sa.DECIMAL(precision=3, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'back_percent')
    # ### end Alembic commands ###
