"""change paidPrice to nullable= true

Revision ID: cb8d015967d9
Revises: 15ef422c6ede
Create Date: 2026-08-09 12:57:13.947185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb8d015967d9'
down_revision: Union[str, Sequence[str], None] = '15ef422c6ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'paid_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'paid_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
